config/routes.rb
ChewyExample::Application.routes.draw do
  resources :entertainment
  root to: 'entertainment#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
  acts_as_taggable

  belongs_to :author, class_name: 'Dude'
  update_index 'entertainment#book', :self
end

app/models/dude.rb
class Dude < ActiveRecord::Base
  acts_as_taggable

  has_many :books, foreign_key: :author_id
  has_many :videos, foreign_key: :director_id
  update_index 'entertainment#book', :books
  update_index('entertainment#movie') { videos.movies }
  update_index('entertainment#cartoon') { videos.cartoons}
end

app/models/video.rb
class Video < ActiveRecord::Base
  acts_as_taggable

  belongs_to :director, class_name: 'Dude'
  update_index('entertainment#movie') { self if movie? }
  update_index('entertainment#cartoon') { self if cartoon? }

  validates :kind, inclusion: {in: %w(movie cartoon)}

  scope :movies, ->{ where(kind: 'movie') }
  scope :cartoons, ->{ where(kind: 'cartoon') }

  def movie?
    kind == 'movie'
  end

  def cartoon?
    kind == 'cartoon'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entertainment_controller.rb
class EntertainmentController < ApplicationController
  def index
    # binding.pry
    @search = EntertainmentSearch.new(params[:search] || [])
    @entertainments = @search.search.only(:id).page(params[:page]).load(
      book: { scope: Book.includes(:author) },
      movie: { scope: Video.includes(:director) },
      cartoon: { scope: Video.includes(:director) }
    )
  rescue Elasticsearch::Transport::Transport::Errors::BadRequest => e
    @entertainments = []
    @error = e.message.match(/QueryParsingException\[([^;]+)\]/).try(:[],1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entertainment/index.html.haml
= form_for @search, as: :search, url: entertainment_index_path, method: :get do |f|
  %p
    = f.label :query
    = f.text_field :query
  %p
    = f.label :author_id
    = f.select :author_id, Dude.all.map { |d| [d.name, d.id] }, include_blank: true
  %p
    = f.label :min_year
    = f.text_field :min_year
  %p
    = f.label :max_year
    = f.text_field :max_year
  %p
    = f.label :tag_list
    = f.text_field :tag_list
  %p
    = f.label :sort
    = f.select :sort, EntertainmentSearch.sort_values
  %p
    = f.submit

- if @entertainments.any?
  %dl
    - @entertainments.each do |entertainment|
      %dt
        %h1= entertainment.title
        %strong= entertainment.class
      %dd
        %p= entertainment.year
        %p= entertainment.description
        %p= entertainment.tag_list
  = paginate @entertainments
- else
  - if @error
    = @error
  - else
    Nothing to see here

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChewyExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>